services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: <your-openai-api-key>
      - key: GEMINI_API_KEY
        value: <your-gemini-api-key>

  - type: web
    name: frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend.py --server.port 10000 --server.address 0.0.0.0"
    plan: free
    envVars:
      - key: BACKEND_URL
        value: "https://<your-backend-service-name>.onrender.com/ask"
